# Config file for automatic testing at travis-ci.org
language: python

services:
  - docker

before_install:
  - docker-compose -v
  - docker -v


env:
  - ENVIRONMENT=CI

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# Because we run the test with pytest==4.4.1 we need pluggy>=0.9
# Would be easier to run travis with tox but is not trivial. 
install: pip install -r requirements.txt

matrix:
  include:	
    - name: Test
      python: 3.7
      script: ./scripts/test
    - name: Test Docker image
      python: 3.7
      script: ./scripts/test_docker
